name: Check Branch Naming Convention

on:
  create:
    branches:
      - 'feature/*'
      - 'patch/*'

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Validate branch name
        run: |
          if [[ "${GITHUB_REF}" =~ ^(feature|patch)/[A-Z]+-[0-9]+-.+ ]]; then
            echo "Branch name is valid."
          else
            echo "Branch name is invalid. It must follow the pattern 'feature/<JIRA_ID>-<short_description>' or 'patch/<JIRA_ID>-<short_description>'."
            exit 1
          fi

          
